#!/bin/bash

# Debug script for biometric setup flow

echo "=== MeTrustual Biometric Setup Flow Debug ==="
echo ""
echo "Expected Flow:"
echo "1. App launches → SplashScreen"
echo "2. If not onboarded → OnboardingScreen"
echo "3. User taps 'Get Started' button"
echo "4. Anonymous auth created, UUID saved"
echo "5. Navigate to → BiometricSetupScreen"
echo "6. User sets PIN"
echo "7. Navigate to → ModeSelectionScreen"
echo "8. User completes journey"
echo "9. Navigate to → HomeScreen"
echo ""
echo "=== Checklist ==="
echo "[ ] App shows OnboardingScreen"
echo "[ ] OnboardingScreen button clickable"
echo "[ ] Console shows: '📝 Starting onboarding...'"
echo "[ ] Console shows: '✅ Onboarding completed'"
echo "[ ] Console shows: '🆔 Got UID: xxx'"
echo "[ ] Console shows: '🔀 Navigating to: /biometric-setup/xxx'"
echo "[ ] BiometricSetupScreen appears"
echo "[ ] Console shows: '🔐 BiometricSetupScreen initialized with UID: xxx'"
echo ""
echo "If BiometricSetupScreen doesn't appear, check:"
echo "1. Is the UID being retrieved correctly?"
echo "2. Is context.push() throwing an error?"
echo "3. Is the route registered in app_router.dart?"
echo "4. Are there any Dart/Flutter compilation errors?"
